### ISSUE TITLE
Automate sync of quick links

### ISSUE THREAD

**Issue by dadatuputi** [dadatuputi/aflinks#1]
There are two sources for quick links that I'm aware of:

https://www.my.af.mil/gcss-af/USAF/ep/browse.do?programId=t7F11BC9F7894301901789469137C0003&channelPageId=s6925EC1356510FB5E044080020E329A9

and 

https://www.my.af.mil/gcss-af/USAF/ep/browse.do?categoryId=p7F11BC9F789430190178946F7E140005&channelPageId=sD22E5184744EFC540174558CFFA50008

Both require authenticated access to the portal. The second link, however, makes a request to https://www.my.af.mil/gcss-af/USAF/api/quicklinks/cached?categorized=true&id=p7F11BC9F789430190178946F7E140005&siteId=sD22E5184744EFC540174558CFFA50008, which does _not_ require authentication. 

I want to add a github action that will regularly download this list and rebuild the webpage to keep the links current.

**Comment by hattmo** [comment]
It appears that the like that didn't require auth now requires auth

**Comment by hattmo** [comment]
[This url](https://github.com/dadatuputi/aflinks/pull/3/files#diff-755913a300f761834c95431b4203471d469913d679df70135523e5bc48593dc1R5) will forward sometimes to the my.af.mil SSO page which causes the api request to obviously fail.  strangely it doesn't seem to be an authenticated session using something like cookies or jwt or even the ssl connection, becuase if it SSO from a separate browser, then the node process will start working.  My hypothisis is its based on source IP addr or some other weird interaction.  BL is that the GH Action wont work becuase the host the updater runs on can never auth to my.af.mil SSO.  Could be some other issue on my end but the same result happens in the GH Runner.

**Comment by hattmo** [comment]
Look at [The runs in my repo](https://github.com/hattmo/aflinks/actions).  I just ran it and it worked with no changes to the repo.  The failed runs are failing because they got back the SSO sign in page instead of the JSON.  I'm at a loss lol.

**Comment by dadatuputi** [comment]
I tested it from a VPN and it worked (from home). I'm at another location now and the URL tried to get me to log in. I tried the URL again and it worked. I'm not sure if it's some load balancing or what. Maybe having it try multiple times for a few minutes before failing would work.

**Comment by hattmo** [comment]
I think it would be nice to deploy from this action as well, but I'm not sure how you want it to be hosted.  I was thinking to gen a docker container

**Comment by dadatuputi** [comment]
The site is hosted here through GitHub pages, so index.html is what's served up

**Comment by hattmo** [comment]
I made a ton of changes to the PR that should address the other issues.

**Comment by dadatuputi** [comment]
I was getting the portal login on multiple browsers. When I authenticated in one, it stopped requiring authentication in the other. It seems like the cached page is expiring and requires authentication then it's accessible some time without authentication.

**Comment by dadatuputi** [comment]
Having the job run during the day on a work day would be the best time in that case.

**Comment by hattmo** [comment]
> I was getting the portal login on multiple browsers. When I authenticated in one, it stopped requiring authentication in the other. It seems like the cached page is expiring and requires authentication then it's accessible some time without authentication.

That's the behavior I'm getting on my desktop but that doesn't explain why it works in the CICD agent.
