### ISSUE TITLE
Sharepoint Sites

### ISSUE THREAD

**Issue by Rexfordbelleville** [dadatuputi/aflinks#33]
### Link Title

Sharepoint Sites

### Link URL

https://www.my.af.mil/gcss-af/USAF/ep/browse.do?categoryId=p88B4F00B408E088F01419EEE5C3D1C7F&channelPageId=s6925EC1350340FB5E044080020E329A9

### Comment

This link no longer works, can it be replaced with the right one?

**Comment by dadatuputi** [comment]
I'll close this, but if you do get a working link please reopen!
