### ISSUE TITLE
[LINK]: PRMS (Personnel Recovery Mission Software)

### ISSUE THREAD

**Issue by Syreious** [dadatuputi/aflinks#34]
### Link Title

PRMS (Personnel Recovery Mission Software) (.mil only)

### Link URL

https://prmsglobal.prms.af.mil/

### Comment

Used for ISOPREP purposes and other PR functions

**Comment by dadatuputi** [comment]
Thanks for the link. Tested and seems to only work on .mil (desktop anywhere).
